# Global configuration with settings and hyperparameters for prediction only.

General:
  bbox_color: "#17365C"            # (str) Color hex code for bounding box visualization
  mask_color: "#5C1D17"            # (str) Color hex code for mask visualization
  polygon_color: "#17365C"         # (str) Color hex code for initial polygon visualization
  final_polygon_color: "#D2DBA4"   # (str) Color hex code for final polygon visualization

CrossSectionDetector:
  model: "weights/yolov8m.pt"      # (str) Path to the YOLO model weights file
  device: "cuda:0"                 # (str) Computing device ('cuda:X' or 'cpu')
  iou: 0.7                         # (float) Intersection over Union threshold for NMS
  conf: 0.25                       # (float) Object confidence threshold for detection (default: 0.25)
  imgsz: 640                       # (int) Input image size (pixels)

MaskGenerator:
  sam_chkpt: "weights/sam_vit_h.pth"  # (str) Path to the SAM model checkpoint file
  model_type: "vit_h"                 # (str) SAM model variant ('vit_h', 'vit_l', or 'vit_b')
  device: "cuda:1"                    # (str) Computing device ('cuda:X' or 'cpu')
  multimask: false                    # (bool) Generate multiple masks per input prompt (true/false)

PolygonSimplifier:
  factor_arclength: 0.01              # (float) Simplification factor based on polygon arclength

ParameterOptimizer:
  weight_overlap: 1.0                 # (float) Weight factor for polygon overlap metric
  weight_distance: 1.0                # (float) Weight factor for polygon distance metric
  weight_aspect_ratio: 1.0            # (float) Weight factor for polygon aspect ratio metric
  maxiter: 1000                       # (int) Maximum number of global optimization iterations (default: 1000)
  initial_temp: 5230                  # (float) Initial temperature for global search; higher values facilitate wider search (default: 5230)
